# This is a basic workflow to help you get started with Actions

name: Example Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  example-job:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run my test script
        env:
          my-var: False
        run: |
          python ./tutorial-code-samples/github-actions/src/my-test-script.py
